# Sorane (SRN) Configuration

# Directory Paths
# All paths are relative to the project root
directories:
  site: "site"
  dist: "dist"
  content: "site/content"
  fonts: "site/fonts"
  data: "site/data"

# Identity & DID (did:web)
identity:
  domain: "masanork.github.io"
  path: "/srn"

# Font Style Aliases
# These can be referenced in Markdown frontmatter (e.g. font: GJM)
fontStyles:
  Sans:
    - "NotoSansJP-VariableFont_wght.ttf"
    - "NotoSansSC-VariableFont_wght.ttf"
    - "NotoSansTC-VariableFont_wght.ttf"
    - "NotoSansKR-VariableFont_wght.ttf"
  Serif:
    - "NotoSerifJP-VariableFont_wght.ttf"
    - "NotoSerifSC-VariableFont_wght.ttf"
    - "NotoSerifTC-VariableFont_wght.ttf"
    - "NotoSerifKR-VariableFont_wght.ttf"
  GJM:
    - "ipamjm.ttf"
    - "acgjm.ttf"
  TOKI:
    - "TOUKIMIN.ttf"
    - "TMIN1501.ttf"
    - "TMIN1502.ttf"
    - "TMIN1503.ttf"
    - "TMIN1504.ttf"
    - "TMIN1505.ttf"
    - "TMIN1506.ttf"
    - "TMIN1507.ttf"
    - "TMIN1508.ttf"
    - "TMIN1509.ttf"
    - "TMIN1510.ttf"
    - "TMIN1511.ttf"
    - "TMIN1601.ttf"
    - "TMIN1602.ttf"
    - "TMIN1603.ttf"
    - "TMIN1604.ttf"
    - "TMINEX1.ttf"
  default: "Sans"
