
# Web/A Form Site Configuration

directories:
  site: "sites/weba"
  dist: "dist/weba"
  content: "sites/weba/content"
  data: "sites/weba/data"

identity:
  domain: "masanork.github.io"
  path: "/weba"
