# My Blog Configuration

directories:
  site: "sites/my-blog"
  dist: "dist/my-blog"
  content: "sites/my-blog/content"
  data: "sites/my-blog/data"

identity:
  domain: "masanork.github.io"
  path: ""
